import Link from "next/link";
import { Footer, Header } from "../page";

export default function Privacy() {
  return <main><Header />
    <section className="subhero shell"><p className="eyebrow">PRODUCT PRIVACY</p><h1>Your preferences. Your choice.</h1><p>Set visibility for every condition while TripSync keeps the plan useful to the whole group.</p><Link className="button dark" href="/signup?next=/trips/new">Create a trip</Link></section>
    <section className="visibility shell"><div className="section-intro"><p className="eyebrow">01 · VISIBILITY</p><div><h2>One need. Three visibility levels.</h2><p>The system may recommend a default, but only the member can change what each item reveals.</p></div></div><div className="visibility-grid">{[["Planning system only", "AI and backend services can generate and validate with it. The organizer and other members do not see the original detail."], ["Planning system + Organizer", "The system and organizer can view it. Other members see only the anonymous result needed for planning."], ["Everyone", "Every member in the trip can view the preference and use it in the shared discussion."]].map(([t,p],i)=><article className={`tone-${i+1}`} key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div><p className="privacy-disclosure">Authorized operations staff may process data when required for security, support, or legal obligations. “Planning system only” controls product visibility; it is not a promise that no authorized person can ever access the data.</p></section>
    <section className="privacy-example"><div className="shell"><p className="eyebrow">02 · FROM PRIVATE TO USEFUL</p><h2>Use the constraint. Protect the person.</h2><div className="privacy-pair"><div><span>PLANNING SYSTEM ONLY</span><p>“I need step-free access throughout the trip.”</p></div><i>→</i><div><span>ANONYMOUS PLAN RESULT</span><p>“All selected locations and transport must be step-free.”</p></div></div></div></section>
    <section className="section shell"><div className="section-intro"><p className="eyebrow">03 · PRODUCT VIEW</p><div><h2>Show the rule in context.</h2><p>This space is reserved for a real privacy-control screen once the product interface is available.</p></div></div><div className="image-placeholder wide"><span>UI PLACEHOLDER</span><strong>Preference visibility controls</strong><small>Only AI · Group summary · Shared with the group</small></div></section>
    <section className="final-cta"><div className="shell"><p className="eyebrow">HONEST INPUT, SHARED DIRECTION</p><h2>Create room for what every traveler needs.</h2><Link className="button light" href="/signup?next=/trips/new">Create a trip</Link></div></section><Footer />
  </main>;
}
